version: '3.2'
services:
  ui:
    build: .
    image: ui
    ports:
      - '3000:80'
    volumes:
      - ./:/frontend
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=dev12345
      - MYSQL_PASSWORD=dev12345
      - MYSQL_USER=dev
      - MYSQL_DATABASE=dev_db


